version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: crypto_postgres
    restart: always
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass
      POSTGRES_DB: crypto_calculator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scraper:
    image: egualdo/crypto-calculator-scraper:latest
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: crypto_scraper
    restart: always
    ports:
      - "7000:7000"

  backend:
    image: egualdo/crypto-calculator-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crypto_backend
    restart: always
    depends_on:
      - db
      - scraper
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=crypto_calculator
      - DB_USER=crypto_user
      - DB_PASSWORD=crypto_pass
      - SCRAPER_SERVICE_URL=http://scraper:7000
    ports:
      - "3001:3001"
    networks:
      default:
        aliases:
          - crypto-calculator-backend-svc

  frontend:
    image: egualdo/crypto-calculator-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crypto_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  postgres_data:
