apiVersion: v1
kind: Service
metadata:
  name: crypto-calculator-backend-svc
  namespace: crypto-calculator
  labels:
    app: crypto-calculator-backend
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: crypto-calculator-backend