apiVersion: v1
kind: Service
metadata:
  name: crypto-calculator-frontend-svc
  namespace: crypto-calculator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    role: crypto-calculator-frontend